### ISSUE TITLE
Segmentation fault while trying to run verse

### ISSUE THREAD

**Issue by adityasundaram** [xgfs/verse#9] opened 2019-02-26 07:21 UTC
I created a bcsr file using the convert python script for a graph with `23,506,056` nodes and `77,166,666` edges. I get a segmentation fault while trying to run verse training. Any suggestions as to how do I enable more logging to identify what's causing this?

Command used - 
./verse -input ../python/out.bcsr -output embed.bin -dim 128 -alpha 0.85 -threads 32 -nsamples 3

**Comment by xgfs** [comment] 2019-02-26 07:49
You can use gdb with 1 thread to identify the root cause. Most typically, it's some dangling nodes that you did not remove from the graph, or some error in the conversion process.

**Comment by adityasundaram** [comment] 2019-02-26 21:21
got it, will recheck my graphs and run with gdb too. Thank you

**Comment by adityasundaram** [comment] 2019-02-26 22:02
I was debugging the code a bit, noticed something odd in the following lines, the n1 * n_hidden results in a negative value, array access of a negative value should be a seg fault right? Is this a result of overflow?

int n1 = irand(nv);
      int n2 = sample_rw(n1);
      cout << "n1 : " << n1 << "n1 * hidden " << n1 * n_hidden << endl;


the actual error as per GDB was - 

run ./verse -input ../python/out_44m.bcsr -output embed_44m.bin -dim 256 -alpha 0.85 -threads 1 -nsamples 10 -steps 100
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /lfs1/verse/src/verse ./verse -input ../python/out_44m.bcsr -output embed_44m.bin -dim 256 -alpha 0.85 -threads 1 -nsamples 10 -steps 100
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
nv: 17809585, ne: 32234784
Total steps (mil): 1780.96

Program received signal SIGSEGV, Segmentation fault.
update (label=0, bias=14.392662, w_t=0x7ffb4c896480, w_s=0x7ffc0a14b880) at verse.cpp:152
152        score += w_s[c] * w_t[c];

**Comment by adityasundaram** [comment] 2019-02-26 22:16
Is there anyway to run verse for such large graphs?

**Comment by xgfs** [comment] 2019-02-27 08:01
Could you also specify the system & the compiler you are using? I will fix the bug shortly, I am just interested in why it did not occur on my machines.

**Comment by xgfs** [comment] 2019-02-27 08:24
Should be fixed.

**Comment by xgfs** [comment] 2019-03-02 10:48
If the problem persists, feel free to reopen.

**Closed by xgfs** 2019-03-02 10:48 UTC

**Comment by adityasundaram** [comment] 2019-03-13 02:41
Was able to run this for a graph with close to 42 mill vertices and 270 million edges. It worked! Thank you
